Repository OCA/queue, pull requests merged in 2019-03, with the labels that each got.

#132 [FIX/IMP] a couple issues observed during startup
  queue_job/jobrunner/channels.py
  queue_job/jobrunner/runner.py
Labels: approved, work in progress

#117 [12.0] [MIG] Queue Job Cron
  .gitignore
  queue_job_cron/README.rst
  queue_job_cron/__init__.py
  queue_job_cron/__manifest__.py
  queue_job_cron/data/data.xml
  queue_job_cron/models/__init__.py
  queue_job_cron/models/ir_cron.py
  queue_job_cron/readme/CONFIGURATION.rst
  queue_job_cron/readme/CONTRIBUTORS.rst
  queue_job_cron/readme/DESCRIPTION.rst
  queue_job_cron/readme/INSTALL.rst
  queue_job_cron/readme/USAGE.rst
  queue_job_cron/static/description/index.html
  queue_job_cron/tests/__init__.py
  queue_job_cron/tests/test_queue_job_cron.py
  queue_job_cron/views/ir_cron_view.xml
  setup/queue_job_cron/odoo/addons/queue_job_cron
  setup/queue_job_cron/setup.py
Labels: approved, needs review

#135 [FIX/IMP] a couple issues observed during startup, take 2 :)
  queue_job/jobrunner/channels.py
  queue_job/jobrunner/runner.py
Labels: approved, needs review

#111 [11.0] queue_job: ease testing
  queue_job/models/base.py
  queue_job/readme/USAGE.rst
Labels: approved

#138 [10.0] queue_job: ease testing
  queue_job/models/base.py
  queue_job/readme/USAGE.rst
Labels: approved

#131 [12.0][FIX] under pressure
  queue_job/controllers/main.py
  queue_job/exception.py
  queue_job/jobrunner/runner.py
Labels: approved, needs review
