Repository OCA/queue, pull requests merged in 2020-06, with the labels that each got.

#208 [13.0] Port jobrunner as a worker
  queue_job/jobrunner/__init__.py
  queue_job/jobrunner/runner.py
  queue_job/readme/HISTORY.rst
Labels: approved, bot is merging ⏳

#195 [12.0] Port jobrunner as a worker
  queue_job/jobrunner/__init__.py
  queue_job/jobrunner/runner.py
  queue_job/readme/HISTORY.rst
Labels: bot is merging ⏳

#230 avoid singleton error to search function job
  queue_job/models/queue_job.py
Labels: approved, bot is merging ⏳

#236 [13.0][FWD] #150 [IMP] add job helper for simplifying testing
  queue_job/tests/common.py
Labels: bot is merging ⏳

#197 [12.0] Add export_async_schedule
  .travis.yml
  base_export_async/__manifest__.py
  base_export_async/i18n/base_export_async.pot
  base_export_async/i18n/de.po
  base_export_async/i18n/zh_CN.po
  base_export_async/migrations/12.0.1.1.0/post-migrate.py
  base_export_async/migrations/12.0.1.1.0/pre-migrate.py
  base_export_async/models/delay_export.py
  base_export_async/readme/CONTRIBUTORS.rst
  base_export_async/security/ir_rule.xml
  base_export_async/static/src/js/data_export.js
  base_export_async/tests/test_base_export_async.py
  export_async_schedule/README.rst
  export_async_schedule/__init__.py
  export_async_schedule/__manifest__.py
  export_async_schedule/data/ir_cron.xml
  export_async_schedule/models/__init__.py
  export_async_schedule/models/export_async_schedule.py
  export_async_schedule/readme/CONFIGURE.rst
  export_async_schedule/readme/CONTRIBUTORS.rst
  export_async_schedule/readme/DESCRIPTION.rst
  export_async_schedule/readme/ROADMAP.rst
  export_async_schedule/readme/USAGE.rst
  export_async_schedule/security/ir.model.access.csv
  export_async_schedule/static/description/icon.png
  export_async_schedule/static/description/index.html
  export_async_schedule/tests/__init__.py
  export_async_schedule/tests/test_export_async_schedule.py
  export_async_schedule/views/export_async_schedule_views.xml
  queue_job/tests/common.py
  setup/export_async_schedule/odoo/addons/export_async_schedule
  setup/export_async_schedule/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#237 [13.0] Add mock_with_delay to help testing of jobs
  queue_job/tests/common.py
Labels: approved, bot is merging ⏳, ready to merge

#243 [13.0][FIX] base_import_async do function error message
  base_import_async/models/base_import_import.py
Labels: approved, bot is merging ⏳
