Repository OCA/queue, pull requests merged in 2020-03, with the labels that each got.

#150 [12.0][IMP] add job helper for simplifying testing
  queue_job/tests/common.py
Labels: approved, ready to merge

#216 [12.0][MIG] queue_job_subscribe
  queue_job_subscribe/README.rst
  queue_job_subscribe/__manifest__.py
  queue_job_subscribe/readme/CONTRIBUTORS.rst
  queue_job_subscribe/readme/DESCRIPTION.rst
  queue_job_subscribe/readme/USAGE.rst
  queue_job_subscribe/tests/test_job_subscribe.py
Labels: approved

#217 [12.0][FIX] round icon
  queue_job/static/description/icon.png
  queue_job/static/description/icon.svg
Labels: approved

#218 [13.0][FIX] round icon
  queue_job/static/description/icon.png
  queue_job/static/description/icon.svg
Labels: approved

#219 [FIX] queue_job_cron: use the complete name of the channel when launching a cron
  queue_job_cron/models/ir_cron.py
  queue_job_cron/tests/test_queue_job_cron.py
Labels: approved, bot is merging ⏳
