Repository OCA/queue, pull requests merged in 2020-11, with the labels that each got.

#279 [12.0] Fix development status key (Stable → Production/Stable)
  base_import_async/__manifest__.py
  test_base_import_async/__manifest__.py
Labels: bot is merging ⏳

#278 [13.0] Fix development status key (Stable → Production/Stable)
  base_import_async/__manifest__.py
  test_base_import_async/__manifest__.py
Labels: bot is merging ⏳

#215 [FIX] Flush pending updates immediately when storing job data
  queue_job/controllers/main.py
Labels: bot is merging ⏳

#280 Remove warning when @job decorator is used
  queue_job/job.py
Labels: approved, bot is merging ⏳

#258 Store worker's PID when a job is started
  queue_job/job.py
  queue_job/models/queue_job.py
  queue_job/views/queue_job_views.xml
  test_queue_job/tests/test_job.py
Labels: approved, bot is merging ⏳

#281 [13.0] Refactor storage of job records with "sudo" support
  queue_job/__manifest__.py
  queue_job/fields.py
  queue_job/i18n/queue_job.pot
  queue_job/job.py
  queue_job/migrations/13.0.3.2.0/pre-migration.py
  queue_job/models/queue_job.py
  queue_job/readme/USAGE.rst
  queue_job/tests/test_json_field.py
  test_queue_job/tests/test_job.py
Labels: approved, bot is merging ⏳

#277 [13.0] Fix channel name in jobs delayed for crons
  queue_job_cron/models/ir_cron.py
  queue_job_cron/tests/test_queue_job_cron.py
Labels: bot is merging ⏳

#287 [10.0][FIX] migration script robustness
  queue_job/migrations/10.0.1.0.0/end-migration.py
Labels: bot is merging ⏳, needs review

#289 [14.0] Migration of queue_job
  .pre-commit-config.yaml
  queue_job/__init__.py
  queue_job/__manifest__.py
  queue_job/exception.py
  queue_job/fields.py
  queue_job/job.py
  queue_job/jobrunner/__init__.py
  queue_job/jobrunner/channels.py
  queue_job/migrations/13.0.1.2.0/post-migrate-queue-job.py
  queue_job/migrations/13.0.2.0.0/post-migration.py
  queue_job/migrations/13.0.3.2.0/pre-migration.py
  queue_job/models/__init__.py
  queue_job/models/base.py
  queue_job/models/ir_model_fields.py
  queue_job/models/queue_job.py
  queue_job/models/queue_job_channel.py
  queue_job/models/queue_job_function.py
  queue_job/readme/CONTRIBUTORS.rst
  queue_job/readme/HISTORY.rst
  queue_job/security/ir.model.access.csv
  queue_job/static/description/icon.svg
  queue_job/tests/common.py
  queue_job/tests/test_model_job_channel.py
  queue_job/views/queue_job_channel_views.xml
  queue_job/views/queue_job_function_views.xml
  queue_job/views/queue_job_menus.xml
  queue_job/views/queue_job_views.xml
  queue_job/wizards/__init__.py
  queue_job/wizards/queue_jobs_to_done.py
  queue_job/wizards/queue_jobs_to_done_views.xml
  queue_job/wizards/queue_requeue_job.py
  queue_job/wizards/queue_requeue_job_views.xml
  queue_job_cron/__manifest__.py
  queue_job_subscribe/__manifest__.py
  requirements.txt
  setup/queue_job/odoo/addons/queue_job
  setup/queue_job/setup.py
  setup/test_queue_job/odoo/addons/test_queue_job
  setup/test_queue_job/setup.py
  test_queue_job/__manifest__.py
  test_queue_job/models/test_models.py
  test_queue_job/tests/common.py
  test_queue_job/tests/test_job.py
  test_queue_job/tests/test_job_channels.py
Labels: approved, bot is merging ⏳

#290 [FIX] queue_job: USAGE update
  queue_job/readme/USAGE.rst
Labels: bot is merging ⏳
