Repository OCA/queue, pull requests merged in 2021-02, with the labels that each got.

#303 [13.0] Change technical fields to read-only
  queue_job/models/queue_job.py
Labels: bot is merging ⏳

#305 [13.0] Optimize queue.job creation
  queue_job/controllers/main.py
  queue_job/job.py
  queue_job/models/queue_job.py
  queue_job/tests/test_model_job_function.py
Labels: approved, bot is merging ⏳

#302 [13.0] Remove initial create notification and follower
  queue_job/models/queue_job.py
  test_queue_job/tests/test_job.py
Labels: approved, bot is merging ⏳

#310 [13.0] Add model in search view / group by
  queue_job/views/queue_job_views.xml
Labels: approved, bot is merging ⏳

#313 [14][queue_job] Vacuum done jobs in batch
  queue_job/models/queue_job.py
Labels: approved, bot is merging ⏳, ready to merge
