Repository OCA/queue, pull requests merged in 2021-05, with the labels that each got.

#340 [14.0][FIX] queue_job: replace deprecated use of logging.warn
  queue_job/controllers/main.py
  queue_job/models/base.py
Labels: approved, bot is merging ⏳

#334 [14.0] [IMP] Store job execution information + wizard to terminate a job + test
  queue_job/__manifest__.py
  queue_job/job.py
  queue_job/models/queue_job.py
  queue_job/security/ir.model.access.csv
  queue_job/views/queue_job_views.xml
  queue_job/wizards/__init__.py
  queue_job/wizards/queue_terminate_job.py
  queue_job/wizards/queue_terminate_job_views.xml
  test_queue_job/models/test_models.py
  test_queue_job/tests/test_job.py
Labels: approved, bot is merging ⏳, ready to merge

#345 Revert "[14.0] [IMP] Store job execution information + wizard to terminate a job + test"
  queue_job/__manifest__.py
  queue_job/job.py
  queue_job/models/queue_job.py
  queue_job/security/ir.model.access.csv
  queue_job/views/queue_job_views.xml
  queue_job/wizards/__init__.py
  queue_job/wizards/queue_terminate_job.py
  queue_job/wizards/queue_terminate_job_views.xml
  test_queue_job/models/test_models.py
  test_queue_job/tests/test_job.py
Labels: bot is merging ⏳, needs review

#344 [12.0][FIX] missing attachment type
  base_import_async/models/base_import_import.py
Labels: bot is merging ⏳

#242 [FIX] force binary file type
  base_import_async/models/base_import_import.py
Labels: bot is merging ⏳

#338 [FIX] 14.0 doctests hidden errors
  queue_job/tests/common.py
  queue_job/tests/test_runner_channels.py
  queue_job/tests/test_runner_runner.py
Labels: bot is merging ⏳

#350 [14.0] [IMP] queue_job
  queue_job/models/base.py
  test_queue_job/models/test_models.py
  test_queue_job/tests/__init__.py
  test_queue_job/tests/test_job_auto_delay.py
Labels: approved, bot is merging ⏳
