Repository OCA/queue, pull requests merged in 2021-03, with the labels that each got.

#309 queue_job: add exec time to view some stats
  queue_job/__manifest__.py
  queue_job/job.py
  queue_job/migrations/13.0.3.7.0/pre-migration.py
  queue_job/models/queue_job.py
  queue_job/views/queue_job_views.xml
  test_queue_job/tests/test_job.py
Labels: approved, bot is merging ⏳, ready to merge

#312 [13.0] Fix missing rollback on retried jobs
  queue_job/controllers/main.py
  queue_job/job.py
Labels: approved, bot is merging ⏳, needs review

#311 [12.0] Fix missing rollback on retried jobs
  queue_job/controllers/main.py
  queue_job/job.py
Labels: bot is merging ⏳

#319 [12.0][FIX] queue_job: create/replace queue_job_notify function after migration
  queue_job/migrations/12.0.1.0.1/post-migration.py
Labels: approved, bot is merging ⏳

#320 [10.0][FIX] queue_job: drop trigger when rewriting table in migration
  queue_job/migrations/10.0.1.0.0/post-migration.py
Labels: approved, bot is merging ⏳, ready to merge

#325 [REF] Replace deprecated assertEquals with assertEqual
  test_queue_job/tests/test_job.py
  test_queue_job/tests/test_job_channels.py
  test_queue_job/tests/test_related_actions.py
Labels: approved, bot is merging ⏳

#316 [MIG][10.0] queue_job garbage collector
  queue_job/data/queue_data.xml
  queue_job/models/queue_job.py
Labels: approved, bot is merging ⏳
