Repository OCA/queue, pull requests merged in 2021-11, with the labels that each got.

#384 [15.0] Migration of queue_job
  .pre-commit-config.yaml
  queue_job/__manifest__.py
  queue_job/controllers/main.py
  queue_job/fields.py
  queue_job/job.py
  queue_job/jobrunner/__init__.py
  queue_job/jobrunner/channels.py
  queue_job/models/queue_job_channel.py
  queue_job/models/queue_job_function.py
  queue_job/tests/common.py
  queue_job/tests/test_model_job_channel.py
  queue_job/tests/test_model_job_function.py
  queue_job/tests/test_queue_job_protected_write.py
  setup/queue_job/odoo/addons/queue_job
  setup/queue_job/setup.py
  setup/test_queue_job/odoo/addons/test_queue_job
  setup/test_queue_job/setup.py
  test_queue_job/__manifest__.py
  test_queue_job/tests/common.py
  test_queue_job/tests/test_autovacuum.py
  test_queue_job/tests/test_job.py
  test_queue_job/tests/test_job_channels.py
  test_queue_job/tests/test_related_actions.py
Labels: approved, bot is merging ⏳

#382 [14.0][FIX] queue_job_cron: channel_id must be storable.
  queue_job_cron/models/ir_cron.py
Labels: bot is merging ⏳

#390 queue_job: fix typo in USAGE.rst
  queue_job/readme/USAGE.rst
Labels: bot is merging ⏳

#387 [14.0][IMP][FWP] queue_job current company
  queue_job/job.py
  test_queue_job/tests/test_job.py
Labels: approved, ready to merge, bot is merging ⏳

#377 [11.0][MIG] queue_job_cron
  queue_job_cron/README.rst
  queue_job_cron/__init__.py
  queue_job_cron/__manifest__.py
  queue_job_cron/data/data.xml
  queue_job_cron/i18n/de.po
  queue_job_cron/i18n/fr.po
  queue_job_cron/i18n/queue_job_cron.pot
  queue_job_cron/i18n/zh_CN.po
  queue_job_cron/models/__init__.py
  queue_job_cron/models/ir_cron.py
  queue_job_cron/readme/CONFIGURATION.rst
  queue_job_cron/readme/CONTRIBUTORS.rst
  queue_job_cron/readme/DESCRIPTION.rst
  queue_job_cron/readme/INSTALL.rst
  queue_job_cron/readme/USAGE.rst
  queue_job_cron/static/description/icon.png
  queue_job_cron/static/description/index.html
  queue_job_cron/tests/__init__.py
  queue_job_cron/tests/test_queue_job_cron.py
  queue_job_cron/views/ir_cron_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#362 [DOC][14.0] describe how to write queue.job.function in case of function defined in abstract model
  queue_job/readme/USAGE.rst
Labels: bot is merging ⏳
