Repository OCA/queue, pull requests merged in 2021-09, with the labels that each got.

#347 [IMP] queue_job: Add cancelled state to queue.job
  queue_job/job.py
  queue_job/models/queue_job.py
  queue_job/tests/__init__.py
  queue_job/tests/test_wizards.py
  queue_job/views/queue_job_views.xml
Labels: approved, bot is merging ⏳

#359 [14.0][MIG] - queue_job_subscribe
  .pre-commit-config.yaml
  queue_job_subscribe/__manifest__.py
  queue_job_subscribe/tests/test_job_subscribe.py
  setup/queue_job_subscribe/odoo/addons/queue_job_subscribe
  setup/queue_job_subscribe/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#373 [13.0] Vacuum done jobs in batch
  queue_job/models/queue_job.py
Labels: approved, bot is merging ⏳

#358 [IMP] no need for base_sparse_field anymore since 0f5ec1
  queue_job/__manifest__.py
Labels: bot is merging ⏳
