Repository OCA/queue, pull requests merged in 2022-05, with the labels that each got.

#393 [14.0][MIG] queue_job_batch, test_queue_job_batch: Migration to 14.0
  queue_job_batch/README.rst
  queue_job_batch/__init__.py
  queue_job_batch/__manifest__.py
  queue_job_batch/data/queue_job_channel_data.xml
  queue_job_batch/data/queue_job_function_data.xml
  queue_job_batch/i18n/fr.po
  queue_job_batch/i18n/queue_job_batch.pot
  queue_job_batch/models/__init__.py
  queue_job_batch/models/queue_job.py
  queue_job_batch/models/queue_job_batch.py
  queue_job_batch/readme/CONTRIBUTORS.rst
  queue_job_batch/readme/CREDITS.rst
  queue_job_batch/readme/DESCRIPTION.rst
  queue_job_batch/readme/USAGE.rst
  queue_job_batch/security/ir.model.access.csv
  queue_job_batch/security/security.xml
  queue_job_batch/static/description/icon.png
  queue_job_batch/static/description/icon.svg
  queue_job_batch/static/description/index.html
  queue_job_batch/static/src/js/systray.js
  queue_job_batch/static/src/scss/systray.scss
  queue_job_batch/static/src/xml/systray.xml
  queue_job_batch/views/assets_backend.xml
  queue_job_batch/views/queue_job_batch_views.xml
  queue_job_batch/views/queue_job_views.xml
  setup/queue_job_batch/odoo/addons/queue_job_batch
  setup/queue_job_batch/setup.py
  setup/test_queue_job_batch/odoo/addons/test_queue_job_batch
  setup/test_queue_job_batch/setup.py
  test_queue_job_batch/README.rst
  test_queue_job_batch/__init__.py
  test_queue_job_batch/__manifest__.py
  test_queue_job_batch/i18n/fr.po
  test_queue_job_batch/i18n/test_queue_job_batch.pot
  test_queue_job_batch/readme/CONTRIBUTORS.rst
  test_queue_job_batch/readme/CREDITS.rst
  test_queue_job_batch/readme/DESCRIPTION.rst
  test_queue_job_batch/static/description/icon.png
  test_queue_job_batch/static/description/icon.svg
  test_queue_job_batch/static/description/index.html
  test_queue_job_batch/tests/__init__.py
  test_queue_job_batch/tests/test_queue_job_batch.py
Labels: approved, ready to merge, bot is merging ⏳

#429 [IMP] queue_job: Recover gracefully when the CPU limit is reached
  queue_job/jobrunner/__init__.py
Labels: bot is merging ⏳

#428 [IMP] queue_job: Recover gracefully when the CPU limit is reached
  queue_job/jobrunner/__init__.py
Labels: bot is merging ⏳

#432 [13.0] Add storage of context in jobs recordsets
  queue_job/fields.py
  queue_job/job.py
  queue_job/models/base.py
  queue_job/readme/USAGE.rst
  queue_job/tests/test_json_field.py
  test_queue_job/models/test_models.py
  test_queue_job/tests/test_json_field.py
Labels: approved, bot is merging ⏳
