Repository OCA/queue, pull requests merged in 2022-04, with the labels that each got.

#420 Add copier template
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  base_export_async/data/config_parameter.xml
  base_export_async/data/cron.xml
  base_export_async/models/delay_export.py
  base_export_async/security/ir_rule.xml
  base_export_async/static/src/js/data_export.js
  base_export_async/static/src/xml/base.xml
  base_export_async/tests/test_base_export_async.py
  base_export_async/views/assets.xml
  queue_job/__manifest__.py
  queue_job/models/queue_job.py
  queue_job_cron/__manifest__.py
  queue_job_subscribe/__manifest__.py
Labels: approved

#419 [IMP] queue_job: Recover gracefully when the CPU limit is reached
  queue_job/jobrunner/__init__.py
Labels: approved, ready to merge, bot is merging ⏳

#379 [12.0] FIX queue_job avoiding AccessDenied when loading the module in an instance with list_db = False
  queue_job/jobrunner/runner.py
Labels: approved, bot is merging ⏳

#409 [RFC] jobrunner cli
  queue_job/jobrunner/__main__.py
Labels: bot is merging ⏳

#410 [MIG][15.0] queue_job_cron to version 15.0
  .pre-commit-config.yaml
  queue_job_cron/__manifest__.py
  setup/queue_job_cron/odoo/addons/queue_job_cron
  setup/queue_job_cron/setup.py
Labels: approved, ready to merge, bot is merging ⏳
