Repository OCA/queue, pull requests merged in 2022-11, with the labels that each got.

#478 [15.0][PORT] queue_job: jobrunner cli from 14.0 to 15.0
  queue_job/jobrunner/__main__.py
Labels: bot is merging ⏳

#471 [16.0][FW] queue_job: multiple ports from 14.0
  queue_job/__manifest__.py
  queue_job/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#481 [15.0] [FIX] Update pre-commit rules
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: bot is merging ⏳

#482 [16.0] [FIX] Update pre-commit rules
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#476 [15.0][FW] queue_job: port queue dependencies from 14.0
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/controllers/main.py
  queue_job/delay.py
  queue_job/job.py
  queue_job/jobrunner/channels.py
  queue_job/models/base.py
  queue_job/models/queue_job.py
  queue_job/readme/USAGE.rst
  queue_job/static/lib/vis/vis-network.min.css
  queue_job/static/lib/vis/vis-network.min.js
  queue_job/static/src/js/queue_job_fields.js
  queue_job/static/src/scss/queue_job_fields.scss
  queue_job/tests/__init__.py
  queue_job/tests/common.py
  queue_job/tests/test_delayable.py
  queue_job/tests/test_model_job_channel.py
  queue_job/views/queue_job_views.xml
  queue_job_cron_jobrunner/models/queue_job.py
  queue_job_cron_jobrunner/tests/test_queue_job.py
  test_queue_job/models/test_models.py
  test_queue_job/tests/__init__.py
  test_queue_job/tests/test_delay_mocks.py
  test_queue_job/tests/test_delayable.py
  test_queue_job/tests/test_dependencies.py
  test_queue_job/tests/test_job.py
Labels: approved, ready to merge, bot is merging ⏳

#484 [14.0] Update pre-commit conf
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: needs review

#479 [14.0][PORT] queue_job_cron_jobrunner: backport from 15.0 to 14.0 for queue_job_cron_jobrunner from 15.0 to 14.0
  README.md
  queue_job_cron_jobrunner/README.rst
  queue_job_cron_jobrunner/__init__.py
  queue_job_cron_jobrunner/__manifest__.py
  queue_job_cron_jobrunner/data/ir_cron.xml
  queue_job_cron_jobrunner/i18n/queue_job_cron_jobrunner.pot
  queue_job_cron_jobrunner/models/__init__.py
  queue_job_cron_jobrunner/models/ir_cron.py
  queue_job_cron_jobrunner/models/queue_job.py
  queue_job_cron_jobrunner/readme/CONFIGURE.rst
  queue_job_cron_jobrunner/readme/CONTRIBUTORS.rst
  queue_job_cron_jobrunner/readme/DESCRIPTION.rst
  queue_job_cron_jobrunner/readme/ROADMAP.rst
  queue_job_cron_jobrunner/static/description/icon.png
  queue_job_cron_jobrunner/static/description/index.html
  queue_job_cron_jobrunner/tests/__init__.py
  queue_job_cron_jobrunner/tests/test_queue_job.py
  queue_job_cron_jobrunner/views/ir_cron.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_import_async/odoo/addons/base_import_async
  setup/queue_job_cron_jobrunner/odoo/addons/queue_job_cron_jobrunner
  setup/queue_job_cron_jobrunner/setup.py
  setup/test_base_import_async/odoo/addons/test_base_import_async
Labels: bot is merging ⏳

#473 [15.0][FW] queue_job: fix typo in USAGE.rst
  queue_job/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#483 [16.0] queue_job: Forward port queue dependencies from 15.0
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/controllers/main.py
  queue_job/delay.py
  queue_job/i18n/de.po
  queue_job/i18n/es.po
  queue_job/i18n/queue_job.pot
  queue_job/i18n/zh_CN.po
  queue_job/job.py
  queue_job/jobrunner/channels.py
  queue_job/migrations/15.0.1.1.0/post-migration.py
  queue_job/migrations/15.0.1.1.0/pre-migration.py
  queue_job/models/base.py
  queue_job/models/queue_job.py
  queue_job/models/queue_job_function.py
  queue_job/readme/CONTRIBUTORS.rst
  queue_job/readme/USAGE.rst
  queue_job/security/ir.model.access.csv
  queue_job/static/description/index.html
  queue_job/static/lib/vis/vis-network.min.css
  queue_job/static/lib/vis/vis-network.min.js
  queue_job/static/src/views/fields/job_direct_graph/job_direct_graph.esm.js
  queue_job/static/src/views/fields/job_direct_graph/job_direct_graph.scss
  queue_job/static/src/views/fields/job_direct_graph/job_direct_graph.xml
  queue_job/tests/__init__.py
  queue_job/tests/common.py
  queue_job/tests/test_delayable.py
  queue_job/tests/test_model_job_channel.py
  queue_job/tests/test_model_job_function.py
  queue_job/tests/test_wizards.py
  queue_job/views/queue_job_views.xml
  queue_job/wizards/__init__.py
  queue_job/wizards/queue_jobs_to_cancelled.py
  queue_job/wizards/queue_jobs_to_cancelled_views.xml
  test_queue_job/i18n/test_queue_job.pot
  test_queue_job/i18n/zh_CN.po
  test_queue_job/models/test_models.py
  test_queue_job/tests/__init__.py
  test_queue_job/tests/test_delay_mocks.py
  test_queue_job/tests/test_delayable.py
  test_queue_job/tests/test_dependencies.py
  test_queue_job/tests/test_job.py
Labels: approved, ready to merge, bot is merging ⏳

#449 [14.0] base_import_async: add a dedicated channel
  base_import_async/data/queue_job_function_data.xml
Labels: approved, ready to merge, bot is merging ⏳

#480 [IMP] queue_job: add configuration options for
  queue_job/jobrunner/runner.py
Labels: approved, bot is merging ⏳
