Repository OCA/queue, pull requests merged in 2022-08, with the labels that each got.

#443 [14.0][FIX] queue_job: Add base_sparse_field dependency to prevent errors in test if addon not loaded.
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/readme/CONFIGURE.rst
  queue_job/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#453 [14.0][FIX] queue_job: Update documentation to remove unnecessary addon (base_sparse_field) from server_wide_modules.
  queue_job/README.rst
  queue_job/readme/CONFIGURE.rst
  queue_job/static/description/index.html
Labels: approved

#448 [IMP] queue_job: Create job with saved context
  queue_job/fields.py
Labels: approved, ready to merge, bot is merging ⏳

#445 [15.0][MIG] Migration of queue_job_subscribe
  .pre-commit-config.yaml
  queue_job_subscribe/__manifest__.py
  queue_job_subscribe/i18n/ca.po
  queue_job_subscribe/i18n/pt_BR.po
  setup/queue_job_subscribe/odoo/addons/queue_job_subscribe
  setup/queue_job_subscribe/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#454 [14.0][IMP] queue_job: Create job with saved context
  queue_job/fields.py
Labels: bot is merging ⏳

#455 [15.0][IMP] queue_job: Create job with saved context
  queue_job/fields.py
Labels: bot is merging ⏳

#458 [15.0] [IMP] `queue_job`: bump app icon style
  queue_job/static/description/icon.png
  queue_job/static/description/icon.svg
Labels: approved, bot is merging ⏳
