Repository OCA/queue, pull requests merged in 2022-10, with the labels that each got.

#460 [16.0] [MIG] queue_job and test_queue_job
  .pre-commit-config.yaml
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/controllers/main.py
  queue_job/i18n/queue_job.pot
  queue_job/static/description/index.html
  queue_job/tests/common.py
  queue_job/tests/test_model_job_channel.py
  requirements.txt
  setup/queue_job/odoo/addons/queue_job
  setup/queue_job/setup.py
  setup/test_queue_job/odoo/addons/test_queue_job
  setup/test_queue_job/setup.py
  test_queue_job/__manifest__.py
  test_queue_job/i18n/test_queue_job.pot
  test_queue_job/tests/test_job.py
Labels: approved, bot is merging ⏳

#463 [16.0][FW] queue_job: fix typo in USAGE.rst
  queue_job/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#466 [14.0] revert #387
  queue_job/job.py
  test_queue_job/models/test_models.py
  test_queue_job/tests/test_job.py
Labels: approved, bot is merging ⏳

#462 [ADD][14.0] queue_job_context
  queue_job_context/README.rst
  queue_job_context/__init__.py
  queue_job_context/__manifest__.py
  queue_job_context/models/__init__.py
  queue_job_context/models/base.py
  queue_job_context/readme/CONFIGURE.rst
  queue_job_context/readme/CONTRIBUTORS.rst
  queue_job_context/readme/DESCRIPTION.rst
  queue_job_context/static/description/icon.png
  queue_job_context/static/description/index.html
  setup/queue_job_context/odoo/addons/queue_job_context
  setup/queue_job_context/setup.py
Labels: bot is merging ⏳

#472 [16.0][FW] [14.0] Add storage of context in jobs recordsets
  queue_job/fields.py
  queue_job/job.py
  queue_job/models/base.py
  queue_job/readme/USAGE.rst
  queue_job/tests/test_json_field.py
  test_queue_job/models/test_models.py
  test_queue_job/tests/test_json_field.py
Labels: approved, bot is merging ⏳

#475 [15.0][FW] queue_job: multiple ports from 14.0
  queue_job/__manifest__.py
  queue_job/controllers/main.py
  queue_job/job.py
  queue_job/jobrunner/channels.py
  queue_job/migrations/15.0.1.1.0/post-migration.py
  queue_job/migrations/15.0.1.1.0/pre-migration.py
  queue_job/models/base.py
  queue_job/models/queue_job.py
  queue_job/models/queue_job_function.py
  queue_job/readme/CONTRIBUTORS.rst
  queue_job/readme/USAGE.rst
  queue_job/security/ir.model.access.csv
  queue_job/tests/__init__.py
  queue_job/tests/test_model_job_function.py
  queue_job/tests/test_wizards.py
  queue_job/views/queue_job_views.xml
  queue_job/wizards/__init__.py
  queue_job/wizards/queue_jobs_to_cancelled.py
  queue_job/wizards/queue_jobs_to_cancelled_views.xml
  test_queue_job/models/test_models.py
  test_queue_job/tests/test_job.py
Labels: approved, ready to merge, bot is merging ⏳
