Repository OCA/queue, pull requests merged in 2023-06, with the labels that each got.

#542 [16.0] Fix trap_jobs() recordset comparison
  queue_job/tests/common.py
  test_queue_job/tests/test_delay_mocks.py
Labels: bot is merging ⏳

#541 [15.0] Fix trap_jobs() recordset comparison
  queue_job/tests/common.py
  test_queue_job/tests/test_delay_mocks.py
Labels: bot is merging ⏳

#537 [14.0] Fix trap_jobs() recordset comparison
  queue_job/tests/common.py
  test_queue_job/tests/test_delay_mocks.py
Labels: approved, ready to merge, bot is merging ⏳

#493 [14.0][MIG] export_async_schedule: Migration to 14.0
  export_async_schedule/README.rst
  export_async_schedule/__init__.py
  export_async_schedule/__manifest__.py
  export_async_schedule/data/ir_cron.xml
  export_async_schedule/i18n/export_async_schedule.pot
  export_async_schedule/i18n/fr.po
  export_async_schedule/models/__init__.py
  export_async_schedule/models/export_async_schedule.py
  export_async_schedule/readme/CONFIGURE.rst
  export_async_schedule/readme/CONTRIBUTORS.rst
  export_async_schedule/readme/CREDITS.rst
  export_async_schedule/readme/DESCRIPTION.rst
  export_async_schedule/readme/ROADMAP.rst
  export_async_schedule/readme/USAGE.rst
  export_async_schedule/security/ir.model.access.csv
  export_async_schedule/static/description/icon.png
  export_async_schedule/static/description/index.html
  export_async_schedule/tests/__init__.py
  export_async_schedule/tests/test_export_async_schedule.py
  export_async_schedule/views/export_async_schedule_views.xml
  setup/export_async_schedule/odoo/addons/export_async_schedule
  setup/export_async_schedule/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#408 [FIX] queue_job: runner - filedescriptor out of range in select
  queue_job/jobrunner/runner.py
Labels: approved, no stale

#523 [16.0][MIG] base_import_async: Migration to 16.0
  .pre-commit-config.yaml
  base_import_async/README.rst
  base_import_async/__manifest__.py
  base_import_async/i18n/tr.po
  base_import_async/models/base_import_import.py
  base_import_async/models/queue_job.py
  base_import_async/readme/CONTRIBUTORS.rst
  base_import_async/readme/CREDITS.rst
  base_import_async/static/src/xml/import.xml
  base_import_async/views/base_import_async.xml
  setup/base_import_async/odoo/addons/base_import_async
  setup/base_import_async/setup.py
Labels: bot is merging ⏳

#550 [FIX] queue_job: runner - filedescriptor out of range in select
  queue_job/jobrunner/runner.py
Labels: bot is merging ⏳

#551 [FIX] queue_job: runner - filedescriptor out of range in select
  queue_job/jobrunner/runner.py
Labels: bot is merging ⏳
