Repository OCA/queue, pull requests merged in 2024-01, with the labels that each got.

#612 [16.0][IMP] queue_job_cron: Avoid parallel run
  queue_job_cron/models/ir_cron.py
  queue_job_cron/readme/newsfragments/.gitignore
  queue_job_cron/readme/newsfragments/612.feature
  queue_job_cron/tests/test_queue_job_cron.py
  queue_job_cron/views/ir_cron_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#610 [15.0] Remove doctest from get_db_names method to avoid issues with Odoo.sh
  queue_job/jobrunner/runner.py
Labels: approved, bot is merging ⏳

#609 [16.0] Remove doctest from get_db_names method to avoid issues with Odoo.sh
  queue_job/jobrunner/runner.py
Labels: approved, bot is merging ⏳

#620 [16.0][PORT] queu_job: split identity_key hasher to ease reuse (Port from 14.0)
  queue_job/job.py
Labels: approved, merged 🎉

#615 [17.0][MIG] queue_job_cron: Migration to 17.0
  queue_job_cron/README.rst
  queue_job_cron/__init__.py
  queue_job_cron/__manifest__.py
  queue_job_cron/data/data.xml
  queue_job_cron/i18n/de.po
  queue_job_cron/i18n/es.po
  queue_job_cron/i18n/queue_job_cron.pot
  queue_job_cron/i18n/zh_CN.po
  queue_job_cron/models/__init__.py
  queue_job_cron/models/ir_cron.py
  queue_job_cron/pyproject.toml
  queue_job_cron/readme/CONFIGURATION.rst
  queue_job_cron/readme/CONTRIBUTORS.md
  queue_job_cron/readme/DESCRIPTION.md
  queue_job_cron/readme/INSTALL.md
  queue_job_cron/readme/USAGE.md
  queue_job_cron/static/description/icon.png
  queue_job_cron/static/description/index.html
  queue_job_cron/tests/__init__.py
  queue_job_cron/tests/test_queue_job_cron.py
  queue_job_cron/views/ir_cron_view.xml
Labels: bot is merging ⏳

#617 [12.0][BKP] queue_job: identity_key enhancements (Backport from 14.0)
  queue_job/job.py
  queue_job/tests/common.py
  test_queue_job/tests/test_delay_mocks.py
Labels: bot is merging ⏳
