Repository OCA/queue, pull requests merged in 2024-09, with the labels that each got.

#680 [14.0][BKP] queue_job: unify no delay option
  queue_job/README.rst
  queue_job/delay.py
  queue_job/models/base.py
  queue_job/readme/USAGE.rst
  queue_job/utils.py
  test_queue_job/tests/test_delay_mocks.py
Labels: bot is merging ⏳

#643 14.0 fix queue job cron jobrunner
  queue_job_cron_jobrunner/models/queue_job.py
  queue_job_cron_jobrunner/tests/test_queue_job.py
Labels: approved, ready to merge, bot is merging ⏳

#683 [14.0][IMP] queue_job: add filter on Date Created
  queue_job/README.rst
  queue_job/readme/USAGE.rst
  queue_job/static/description/index.html
  queue_job/views/queue_job_views.xml
Labels: approved, bot is merging ⏳

#686 [15.0][FIX] queue_job: Environment.manage() is deprecated
  queue_job/migrations/15.0.1.1.0/post-migration.py
Labels: bot is merging ⏳
