Repository OCA/queue, pull requests merged in 2024-10, with the labels that each got.

#687 [IMP] queue_job: improve Readme/context
  queue_job/readme/CONTEXT.md
Labels: bot is merging ⏳

#689 [fix][17.0] To show dependency graph
  queue_job/static/src/views/fields/job_direct_graph/job_direct_graph.esm.js
  queue_job/views/queue_job_views.xml
Labels: bot is merging ⏳

#679 [IMP] queue_job: Don't raise a warning for valid context
  queue_job/utils.py
  test_queue_job/tests/test_job_auto_delay.py
Labels: approved, ready to merge, bot is merging ⏳

#693 [18.0][MIG] queue_job_cron: Migration to 18.0
  queue_job_cron/README.rst
  queue_job_cron/__init__.py
  queue_job_cron/__manifest__.py
  queue_job_cron/data/data.xml
  queue_job_cron/i18n/de.po
  queue_job_cron/i18n/es.po
  queue_job_cron/i18n/it.po
  queue_job_cron/i18n/queue_job_cron.pot
  queue_job_cron/i18n/zh_CN.po
  queue_job_cron/models/__init__.py
  queue_job_cron/models/ir_cron.py
  queue_job_cron/pyproject.toml
  queue_job_cron/readme/CONFIGURATION.md
  queue_job_cron/readme/CONTRIBUTORS.md
  queue_job_cron/readme/CREDITS.md
  queue_job_cron/readme/DESCRIPTION.md
  queue_job_cron/readme/INSTALL.md
  queue_job_cron/readme/USAGE.md
  queue_job_cron/readme/newsfragments/.gitignore
  queue_job_cron/readme/newsfragments/612.feature
  queue_job_cron/static/description/icon.png
  queue_job_cron/static/description/index.html
  queue_job_cron/tests/__init__.py
  queue_job_cron/tests/test_queue_job_cron.py
  queue_job_cron/views/ir_cron_view.xml
Labels: approved, ready to merge

#695 [18.0][MIG] queue_job_subscribe: Migration to 18.0
  queue_job_subscribe/README.rst
  queue_job_subscribe/__init__.py
  queue_job_subscribe/__manifest__.py
  queue_job_subscribe/i18n/ar.po
  queue_job_subscribe/i18n/bg.po
  queue_job_subscribe/i18n/ca.po
  queue_job_subscribe/i18n/da.po
  queue_job_subscribe/i18n/de.po
  queue_job_subscribe/i18n/el_GR.po
  queue_job_subscribe/i18n/es.po
  queue_job_subscribe/i18n/es_ES.po
  queue_job_subscribe/i18n/fi.po
  queue_job_subscribe/i18n/fr.po
  queue_job_subscribe/i18n/fr_CH.po
  queue_job_subscribe/i18n/hr.po
  queue_job_subscribe/i18n/hr_HR.po
  queue_job_subscribe/i18n/hu.po
  queue_job_subscribe/i18n/it.po
  queue_job_subscribe/i18n/nl.po
  queue_job_subscribe/i18n/pt_BR.po
  queue_job_subscribe/i18n/queue_job_subscribe.pot
  queue_job_subscribe/i18n/sl.po
  queue_job_subscribe/i18n/tr.po
  queue_job_subscribe/i18n/tr_TR.po
  queue_job_subscribe/i18n/zh_CN.po
  queue_job_subscribe/models/__init__.py
  queue_job_subscribe/models/queue_job.py
  queue_job_subscribe/models/res_users.py
  queue_job_subscribe/pyproject.toml
  queue_job_subscribe/readme/CONTRIBUTORS.md
  queue_job_subscribe/readme/CREDITS.md
  queue_job_subscribe/readme/DESCRIPTION.md
  queue_job_subscribe/readme/USAGE.md
  queue_job_subscribe/static/description/icon.png
  queue_job_subscribe/static/description/index.html
  queue_job_subscribe/tests/__init__.py
  queue_job_subscribe/tests/test_job_subscribe.py
  queue_job_subscribe/views/res_users_view.xml
Labels: bot is merging ⏳

#701 [18.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  eslint.config.cjs
  prettier.config.cjs
  queue_job/migrations/18.0.1.0.0/pre-migrate.py
  queue_job/static/src/views/fields/job_direct_graph/job_direct_graph.esm.js
  queue_job/views/queue_job_channel_views.xml
  queue_job/views/queue_job_function_views.xml
  queue_job/views/queue_job_menus.xml
  queue_job/views/queue_job_views.xml
  queue_job/wizards/queue_jobs_to_cancelled_views.xml
  queue_job/wizards/queue_jobs_to_done_views.xml
  queue_job/wizards/queue_requeue_job_views.xml
Labels: help wanted, needs review

#702 [18.0][FIX] queue_job: fix test cases from TestDelayable being skipped
  queue_job/tests/test_delayable.py
Labels: bot is merging ⏳

#703 [17.0][FIX] queue_job: fix test cases from TestDelayable being skipped
  queue_job/tests/test_delayable.py
Labels: bot is merging ⏳

#704 [16.0][FIX] queue_job: fix test cases from TestDelayable being skipped
  queue_job/tests/test_delayable.py
Labels: bot is merging ⏳

#684 [IMP] queue_job_batch: inverse batch order
  queue_job_batch/models/queue_job_batch.py
  queue_job_batch/tests/__init__.py
  queue_job_batch/tests/test_queue_job_batch.py
Labels: approved, bot is merging ⏳

#705 [17.0][FW] queue_job: split identity_key hasher to ease reuse
  queue_job/job.py
Labels: bot is merging ⏳
