Repository OCA/queue, pull requests merged in 2024-12, with the labels that each got.

#715 [18.0] [FWPORT] [IMP] queue_job: Add split method
  queue_job/README.rst
  queue_job/delay.py
  queue_job/readme/USAGE.md
  queue_job/static/description/index.html
  queue_job/tests/__init__.py
  queue_job/tests/test_delayable_split.py
Labels: bot is merging ⏳

#708 [15.0][FIX] queue_job: Post failure after write
  queue_job/models/queue_job.py
Labels: bot is merging ⏳

#717 [FIX] queue_job: fix form view result colspan
  queue_job/views/queue_job_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#720 [16.0][REF] queue_job: Use set.discard(...) instead of SafeSet
  queue_job/jobrunner/channels.py
Labels: approved, bot is merging ⏳

#719 [14.0][REF] queue_job: Use set.discard(...) instead of SafeSet
  queue_job/jobrunner/channels.py
Labels: approved, ready to merge, bot is merging ⏳

#721 [17.0][REF] queue_job: Use set.discard(...) instead of SafeSet
  queue_job/jobrunner/channels.py
Labels: approved, bot is merging ⏳

#722 [18.0][REF] queue_job: Use set.discard(...) instead of SafeSet
  queue_job/jobrunner/channels.py
Labels: bot is merging ⏳

#723 [15.0][REF] queue_job: Use set.discard(...) instead of SafeSet
  queue_job/jobrunner/channels.py
Labels: bot is merging ⏳
