Repository OCA/queue, pull requests merged in 2024-05, with the labels that each got.

#645 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  queue_job/tests/common.py
  queue_job/tests/test_model_job_channel.py
  test_queue_job/tests/test_delay_mocks.py
  test_queue_job/tests/test_json_field.py
Labels: help wanted, needs review, bot is merging ⏳

#642 [FIX] [16.0] queue_job: Add requeue default config parameter for started_delta + improve README
  queue_job/README.rst
  queue_job/data/queue_data.xml
  queue_job/models/queue_job.py
  queue_job/readme/CONFIGURE.rst
  queue_job/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#646 [15.0][FIX] queue_job: Add requeue default config parameter for started_delta
  queue_job/README.rst
  queue_job/data/queue_data.xml
  queue_job/models/queue_job.py
  queue_job/readme/CONFIGURE.rst
  queue_job/static/description/index.html
Labels: bot is merging ⏳

#650 [DOCS] queue_job: make clear the relationship with workers amount
  queue_job/README.rst
  queue_job/readme/CONFIGURE.rst
  queue_job/static/description/index.html
Labels: approved, bot is merging ⏳

#652 [FIX] `JobsTrap` `perform_enqueued_jobs` not working with jobs creating new jobs (issue OCA#651)
  queue_job/tests/common.py
Labels: bot is merging ⏳

#656 [fix] queue_job: JobsTrap.perform_enqueued_jobs
  queue_job/tests/common.py
Labels: bot is merging ⏳

#655 [fix] queue_job: JobsTrap.perform_enqueued_jobs
  queue_job/tests/common.py
Labels: bot is merging ⏳
