Repository OCA/queue, pull requests merged in 2024-04, with the labels that each got.

#635 [17.0] Remove doctest from get_db_names method to avoid issues with Odoo.sh
  queue_job/jobrunner/runner.py
Labels: approved

#634 [13.0][FIX] base_import_async: add import context key as done in base_import
  base_import_async/models/base_import_import.py
Labels: approved, bot is merging ⏳

#623 [16.0][FIX] base_import_async: update OPT_HAS_HEADERS option
  base_import_async/models/base_import_import.py
Labels: approved, bot is merging ⏳

#627 [13.0] [ADD] queue_job_web_notify: send web notifications from queue jobs
  oca_dependencies.txt
  queue_job_web_notify/__init__.py
  queue_job_web_notify/__manifest__.py
  queue_job_web_notify/i18n/fr.po
  queue_job_web_notify/i18n/queue_job_web_notify.pot
  queue_job_web_notify/models/__init__.py
  queue_job_web_notify/models/queue_job.py
  queue_job_web_notify/models/queue_job_function.py
  queue_job_web_notify/readme/CONFIGURE.md
  queue_job_web_notify/readme/CONTEXT.md
  queue_job_web_notify/readme/CONTRIBUTORS.md
  queue_job_web_notify/readme/DESCRIPTION.md
  queue_job_web_notify/readme/ROADMAP.md
  queue_job_web_notify/readme/USAGE.md
  queue_job_web_notify/static/description/icon.png
  queue_job_web_notify/views/queue_job_function.xml
  setup/queue_job_web_notify/odoo/addons/queue_job_web_notify
  setup/queue_job_web_notify/setup.py
Labels: approved, bot is merging ⏳

#611 [14.0] queue_job_cron_jobrunner: avoid concurrent access on ir.cron
  queue_job_cron_jobrunner/models/queue_job.py
  queue_job_cron_jobrunner/tests/test_queue_job.py
Labels: approved, ready to merge, bot is merging ⏳

#641 [16.0][FIX] queue_job: fix warning when triggering stored computed fields
  queue_job/controllers/main.py
Labels: approved, bot is merging ⏳
