Repository OCA/queue, pull requests merged in 2025-01, with the labels that each got.

#732 [18.0][REF] Forward port from 17.0
  queue_job/README.rst
  queue_job/delay.py
  queue_job/readme/USAGE.md
  queue_job/static/description/index.html
  queue_job_cron/views/ir_cron_view.xml
Labels: bot is merging ⏳

#742 [FIX][18.0] queue_job: indicate that run_job need a read/write connection
  queue_job/controllers/main.py
Labels: approved, bot is merging ⏳

#728 [14.0][REF] Clean-up for Python 3
  base_export_async/tests/test_base_export_async.py
  queue_job/delay.py
  queue_job/job.py
  queue_job/jobrunner/channels.py
  queue_job/jobrunner/runner.py
  queue_job/tests/common.py
  queue_job_subscribe/tests/test_job_subscribe.py
  test_queue_job/models/test_models.py
  test_queue_job/tests/test_job.py
  test_queue_job/tests/test_job_channels.py
  test_queue_job/tests/test_job_function.py
Labels: approved, ready to merge

#729 [16.0][UPD] Forward port changes from 14.0 and 15.0
  base_export_async/models/delay_export.py
  base_export_async/tests/test_base_export_async.py
  base_import_async/data/queue_job_function_data.xml
  queue_job/README.rst
  queue_job/delay.py
  queue_job/job.py
  queue_job/jobrunner/channels.py
  queue_job/jobrunner/runner.py
  queue_job/models/queue_job.py
  queue_job/models/queue_job_function.py
  queue_job/readme/USAGE.rst
  queue_job/static/description/index.html
  queue_job/tests/common.py
  queue_job/views/queue_job_views.xml
  queue_job_cron/models/ir_cron.py
  queue_job_cron_jobrunner/models/queue_job.py
  queue_job_cron_jobrunner/tests/test_queue_job.py
  queue_job_subscribe/tests/test_job_subscribe.py
  test_queue_job/models/test_models.py
  test_queue_job/tests/__init__.py
  test_queue_job/tests/test_job.py
  test_queue_job/tests/test_job_function.py
Labels: bot is merging ⏳
