Repository OCA/queue, pull requests merged in 2025-06, with the labels that each got.

#774 [16][FIX] queue_job : replace deprecated invalidate_cache
  queue_job/job.py
Labels: approved, bot is merging ⏳

#772 [14.0][IMP] queue_job: add Priority to Group-By and search
  queue_job/models/queue_job.py
  queue_job/views/queue_job_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#775 [18.0][REF] queue_job: remove deprecated and not used methods
  queue_job/job.py
Labels: approved, ready to merge, bot is merging ⏳

#790 [14.0][IMP] queue_job: filter for retried jobs
  queue_job/views/queue_job_views.xml
Labels: approved, bot is merging ⏳

#791 [14.0][IMP] queue_job: set the columns optional in list view
  queue_job/views/queue_job_views.xml
Labels: approved, bot is merging ⏳

#789 [18.0][IMP] queue_job: filter for retried jobs
  queue_job/views/queue_job_views.xml
Labels: approved, bot is merging ⏳

#793 [18.0][IMP] queue_job: set the columns optional in list view
  queue_job/views/queue_job_views.xml
Labels: approved, bot is merging ⏳

#797 [14.0][FIX] queue_job: Cannot toggle visibility of ETA column
  queue_job/views/queue_job_views.xml
Labels: bot is merging ⏳

#799 [14.0][IMP] queue_job: add index for efficient autovacuum
  queue_job/models/queue_job.py
Labels: bot is merging ⏳
