Repository OCA/queue, pull requests merged in 2025-02, with the labels that each got.

#745 [16.0][IMP] queue_job: improve form view layout for better readability
  queue_job/views/queue_job_views.xml
Labels: bot is merging ⏳

#648 [13.0][FIX] queue_job: triggers stored computed fields before calling 'set_done()'
  queue_job/controllers/main.py
Labels: bot is merging ⏳, stale

#744 [18.0][MIG] queue_job_batch, test_queue_job_batch: Migration to 18.0
  queue_job_batch/README.rst
  queue_job_batch/__init__.py
  queue_job_batch/__manifest__.py
  queue_job_batch/controllers/__init__.py
  queue_job_batch/controllers/webclient.py
  queue_job_batch/data/queue_job_channel_data.xml
  queue_job_batch/data/queue_job_function_data.xml
  queue_job_batch/i18n/es.po
  queue_job_batch/i18n/fr.po
  queue_job_batch/i18n/it.po
  queue_job_batch/i18n/queue_job_batch.pot
  queue_job_batch/migrations/18.0.1.0.0/pre-migrate.py
  queue_job_batch/models/__init__.py
  queue_job_batch/models/queue_job.py
  queue_job_batch/models/queue_job_batch.py
  queue_job_batch/models/res_users.py
  queue_job_batch/pyproject.toml
  queue_job_batch/readme/CONTRIBUTORS.md
  queue_job_batch/readme/CREDITS.md
  queue_job_batch/readme/DESCRIPTION.md
  queue_job_batch/readme/USAGE.md
  queue_job_batch/security/ir.model.access.csv
  queue_job_batch/security/security.xml
  queue_job_batch/static/description/icon.png
  queue_job_batch/static/description/icon.svg
  queue_job_batch/static/description/index.html
  queue_job_batch/static/src/MailCoreWeb.esm.js
  queue_job_batch/static/src/QueueJobBatchModel.esm.js
  queue_job_batch/static/src/Store.esm.js
  queue_job_batch/static/src/components/QueueJobBatchMenu.esm.js
  queue_job_batch/static/src/components/QueueJobBatchMenu.scss
  queue_job_batch/static/src/components/QueueJobBatchMenu.xml
  queue_job_batch/views/queue_job_batch_views.xml
  queue_job_batch/views/queue_job_views.xml
  test_queue_job_batch/README.rst
  test_queue_job_batch/__init__.py
  test_queue_job_batch/__manifest__.py
  test_queue_job_batch/i18n/fr.po
  test_queue_job_batch/i18n/it.po
  test_queue_job_batch/i18n/test_queue_job_batch.pot
  test_queue_job_batch/pyproject.toml
  test_queue_job_batch/readme/CONTRIBUTORS.md
  test_queue_job_batch/readme/CREDITS.md
  test_queue_job_batch/readme/DESCRIPTION.md
  test_queue_job_batch/static/description/icon.png
  test_queue_job_batch/static/description/icon.svg
  test_queue_job_batch/static/description/index.html
  test_queue_job_batch/tests/__init__.py
  test_queue_job_batch/tests/test_queue_job_batch.py
Labels: approved, ready to merge, bot is merging ⏳

#709 [18.0][MIG] queue_job_cron_jobrunner: Migration to 18.0
  queue_job_cron_jobrunner/README.rst
  queue_job_cron_jobrunner/__init__.py
  queue_job_cron_jobrunner/__manifest__.py
  queue_job_cron_jobrunner/data/ir_cron.xml
  queue_job_cron_jobrunner/i18n/it.po
  queue_job_cron_jobrunner/i18n/queue_job_cron_jobrunner.pot
  queue_job_cron_jobrunner/i18n/ro.po
  queue_job_cron_jobrunner/i18n/zh_CN.po
  queue_job_cron_jobrunner/models/__init__.py
  queue_job_cron_jobrunner/models/ir_cron.py
  queue_job_cron_jobrunner/models/queue_job.py
  queue_job_cron_jobrunner/pyproject.toml
  queue_job_cron_jobrunner/readme/CONFIGURE.md
  queue_job_cron_jobrunner/readme/CONTRIBUTORS.md
  queue_job_cron_jobrunner/readme/DESCRIPTION.md
  queue_job_cron_jobrunner/readme/ROADMAP.md
  queue_job_cron_jobrunner/static/description/icon.png
  queue_job_cron_jobrunner/static/description/index.html
  queue_job_cron_jobrunner/tests/__init__.py
  queue_job_cron_jobrunner/tests/test_queue_job.py
  queue_job_cron_jobrunner/views/ir_cron.xml
Labels: approved, ready to merge, bot is merging ⏳
