Repository OCA/queue, pull requests merged in 2025-04, with the labels that each got.

#759 [FIX] queue_job: Adapted migration to properly delete the invalid que…
  queue_job/__manifest__.py
  queue_job/migrations/16.0.2.11.1/pre-migration.py
  queue_job/migrations/16.0.2.9.0/pre-migration.py
Labels: bot is merging ⏳

#762 [FIX] queue_job: Adapted migration to properly delete the invalid cro…
  queue_job/__manifest__.py
  queue_job/migrations/17.0.1.2.0/pre-migration.py
  queue_job/migrations/17.0.1.3.1/pre-migration.py
Labels: bot is merging ⏳

#699 [18.0][MIG] base_import_async: Migration to 18.0
  base_import_async/README.rst
  base_import_async/__init__.py
  base_import_async/__manifest__.py
  base_import_async/data/queue_job_function_data.xml
  base_import_async/i18n/base_import_async.pot
  base_import_async/i18n/es.po
  base_import_async/i18n/it.po
  base_import_async/i18n/tr.po
  base_import_async/models/__init__.py
  base_import_async/models/base_import_import.py
  base_import_async/models/queue_job.py
  base_import_async/pyproject.toml
  base_import_async/readme/CONTRIBUTORS.md
  base_import_async/readme/CREDITS.md
  base_import_async/readme/DESCRIPTION.md
  base_import_async/readme/HISTORY.md
  base_import_async/readme/ROADMAP.md
  base_import_async/readme/USAGE.md
  base_import_async/static/description/icon.png
  base_import_async/static/description/index.html
  base_import_async/static/src/js/import_model.esm.js
  base_import_async/static/src/xml/import_data_sidepanel.xml
  base_import_async/tests/__init__.py
  base_import_async/tests/test_base_import_import.py
Labels: approved, bot is merging ⏳

#738 [14.0][IMP] queue_job: perform_enqueued_jobs should filter the context
  queue_job/tests/common.py
  test_queue_job/tests/test_delay_mocks.py
Labels: approved, ready to merge, bot is merging ⏳
