Repository OCA/queue, pull requests merged in 2025-03, with the labels that each got.

#668 [16.0][IMP] queue_job: HA job runner using session level advisory lock
  queue_job/jobrunner/runner.py
Labels: approved, bot is merging ⏳

#748 [17.0][PORT] queue_job: remove dead jobs requeuer cron and automatically requeue dead jobs
  queue_job/__manifest__.py
  queue_job/controllers/main.py
  queue_job/data/queue_data.xml
  queue_job/job.py
  queue_job/jobrunner/runner.py
  queue_job/migrations/17.0.1.2.0/pre-migration.py
  queue_job/models/__init__.py
  queue_job/models/queue_job.py
  queue_job/models/queue_job_lock.py
  queue_job/readme/CONFIGURE.md
  queue_job/security/ir.model.access.csv
  queue_job/tests/__init__.py
  queue_job/tests/test_requeue_dead_job.py
Labels: approved, ready to merge, bot is merging ⏳

#673 [17.0] [IMP] queue_job: HA job runner using session level advisory lock
  queue_job/jobrunner/runner.py
Labels: approved, bot is merging ⏳

#743 [18.0][IMP] queue_job: perform_enqueued_jobs should filter the context
  queue_job/README.rst
  queue_job/tests/common.py
  test_queue_job/tests/test_delay_mocks.py
Labels: approved, bot is merging ⏳

#757 [18.0][PORT] HA job runner using session level advisory lock
  queue_job/jobrunner/runner.py
Labels: bot is merging ⏳

#681 [17.0][MIG] base_import_async: Migration to V17
  base_import_async/README.rst
  base_import_async/__init__.py
  base_import_async/__manifest__.py
  base_import_async/data/queue_job_function_data.xml
  base_import_async/i18n/base_import_async.pot
  base_import_async/i18n/es.po
  base_import_async/i18n/it.po
  base_import_async/i18n/tr.po
  base_import_async/models/__init__.py
  base_import_async/models/base_import_import.py
  base_import_async/models/queue_job.py
  base_import_async/pyproject.toml
  base_import_async/readme/CONTRIBUTORS.md
  base_import_async/readme/CREDITS.md
  base_import_async/readme/DESCRIPTION.md
  base_import_async/readme/HISTORY.md
  base_import_async/readme/ROADMAP.md
  base_import_async/readme/USAGE.md
  base_import_async/static/description/icon.png
  base_import_async/static/description/index.html
  base_import_async/static/src/js/import_model.esm.js
  base_import_async/static/src/xml/import_data_sidepanel.xml
Labels: approved, bot is merging ⏳, stale
